namespace Mootra
{
    /// <summary>
    /// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    /// </summary>
    public static class IconFont
	{
		/// <summary>
		/// The reference for the calendar plus icon.
		/// </summary>
		public static readonly string CalendarPlus = "\uf271";

		/// <summary>
		/// The reference for the calendar icon.
		/// </summary>
		public static readonly string Calendar = "\uf133";

		/// <summary>
		/// The reference for the trash icon.
		/// </summary>
		public static readonly string Trash = "\uf2ed";
	}
}
